#!/bin/bash

################################################################################
# AWS Amplify Discovery & Audit Script
# Purpose: Document existing Amplify infrastructure for Terraform migration
# Outputs: Markdown, CSV, JSON formats
################################################################################

set -euo pipefail

# Configuration
AWS_PROFILE="kompit"
REGION="${AWS_REGION:-ap-southeast-1}"
OUTPUT_DIR="./amplify-discovery-$(date +%Y%m%d-%H%M%S)"
TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

# Build AWS CLI command prefix
AWS_CMD="aws --profile $AWS_PROFILE"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

################################################################################
# Helper Functions
################################################################################

log_info() {
  echo -e "${GREEN}[INFO]${NC} $1" >&2
}

log_warn() {
  echo -e "${YELLOW}[WARN]${NC} $1" >&2
}

log_error() {
  echo -e "${RED}[ERROR]${NC} $1" >&2
}

log_section() {
  echo -e "\n${BLUE}=== $1 ===${NC}\n" >&2
}

check_dependencies() {
  local deps=("aws" "jq")
  for dep in "${deps[@]}"; do
    if ! command -v "$dep" &>/dev/null; then
      log_error "$dep is not installed. Please install it first."
      exit 1
    fi
  done
}

check_aws_credentials() {
  if ! $AWS_CMD sts get-caller-identity &>/dev/null; then
    log_error "AWS credentials not configured or invalid"
    if [ -n "$AWS_PROFILE" ]; then
      log_error "Check if profile '$AWS_PROFILE' exists: aws configure list-profiles"
    fi
    exit 1
  fi
}

################################################################################
# Main Discovery Functions
################################################################################

discover_amplify_apps() {
  log_section "Discovering Amplify Apps in $REGION"

  local apps_json
  apps_json=$($AWS_CMD amplify list-apps --region "$REGION" 2>&1)

  if [ $? -ne 0 ]; then
    log_error "Failed to list Amplify apps: $apps_json"
    return 1
  fi

  echo "$apps_json" | jq -r '.apps[] | .appId' || echo ""
}

get_app_details() {
  local app_id=$1
  $AWS_CMD amplify get-app --app-id "$app_id" --region "$REGION" 2>/dev/null
}

get_branches() {
  local app_id=$1
  $AWS_CMD amplify list-branches --app-id "$app_id" --region "$REGION" 2>/dev/null
}

get_branch_details() {
  local app_id=$1
  local branch_name=$2
  $AWS_CMD amplify get-branch --app-id "$app_id" --branch-name "$branch_name" --region "$REGION" 2>/dev/null
}

get_domains() {
  local app_id=$1
  $AWS_CMD amplify list-domain-associations --app-id "$app_id" --region "$REGION" 2>/dev/null
}

get_webhooks() {
  local app_id=$1
  $AWS_CMD amplify list-webhooks --app-id "$app_id" --region "$REGION" 2>/dev/null
}

get_backend_environments() {
  local app_id=$1
  $AWS_CMD amplify list-backend-environments --app-id "$app_id" --region "$REGION" 2>/dev/null
}

################################################################################
# Output Generation Functions
################################################################################

init_markdown() {
  local file=$1
  local account_id=$($AWS_CMD sts get-caller-identity --query Account --output text)
  local caller_arn=$($AWS_CMD sts get-caller-identity --query Arn --output text)

  cat >"$file" <<EOF
# AWS Amplify Infrastructure Discovery Report

**Generated:** $TIMESTAMP  
**Region:** $REGION  
**AWS Account:** $account_id  
**AWS Profile:** ${AWS_PROFILE:-default}  
**Generated By:** $caller_arn

---

## Table of Contents
- [Summary](#summary)
- [Applications](#applications)
- [Import Commands](#import-commands)
- [Next Steps](#next-steps)

---

## Summary

EOF
}

init_csv() {
  local file=$1
  cat >"$file" <<'EOF'
"Resource Type","App ID","App Name","Branch Name","Domain","Repository","Platform","Framework","Stage","IAM Role","Created Date","Updated Date","Notes"
EOF
}

generate_markdown_app() {
  local app_json=$1
  local md_file=$2

  local app_id=$(echo "$app_json" | jq -r '.app.appId')
  local app_name=$(echo "$app_json" | jq -r '.app.name')
  local repo=$(echo "$app_json" | jq -r '.app.repository // "N/A"')
  local platform=$(echo "$app_json" | jq -r '.app.platform // "WEB"')
  local iam_role=$(echo "$app_json" | jq -r '.app.iamServiceRoleArn // "N/A"')
  local created=$(echo "$app_json" | jq -r '.app.createTime')
  local updated=$(echo "$app_json" | jq -r '.app.updateTime')
  local default_domain=$(echo "$app_json" | jq -r '.app.defaultDomain')

  cat >>"$md_file" <<EOF

### Application: $app_name

| Property | Value |
|----------|-------|
| **App ID** | \`$app_id\` |
| **Name** | $app_name |
| **Platform** | $platform |
| **Repository** | $repo |
| **Default Domain** | https://$default_domain |
| **IAM Service Role** | $iam_role |
| **Created** | $created |
| **Updated** | $updated |

#### Environment Variables

EOF

  # Environment variables
  local env_vars=$(echo "$app_json" | jq -r '.app.environmentVariables // {}')
  if [ "$env_vars" != "{}" ]; then
    echo "| Variable | Value |" >>"$md_file"
    echo "|----------|-------|" >>"$md_file"
    echo "$env_vars" | jq -r 'to_entries[] | "| `\(.key)` | `\(.value)` |"' >>"$md_file"
  else
    echo "*No environment variables configured*" >>"$md_file"
  fi

  # Custom rules
  echo "" >>"$md_file"
  echo "#### Custom Rules (Redirects/Rewrites)" >>"$md_file"
  echo "" >>"$md_file"

  local custom_rules=$(echo "$app_json" | jq -r '.app.customRules // []')
  if [ "$custom_rules" != "[]" ]; then
    echo '```json' >>"$md_file"
    echo "$custom_rules" | jq '.' >>"$md_file"
    echo '```' >>"$md_file"
  else
    echo "*No custom rules configured*" >>"$md_file"
  fi

  # Build spec
  echo "" >>"$md_file"
  echo "#### Build Specification" >>"$md_file"
  echo "" >>"$md_file"

  local build_spec=$(echo "$app_json" | jq -r '.app.buildSpec // ""')
  if [ -n "$build_spec" ] && [ "$build_spec" != "null" ]; then
    echo '```yaml' >>"$md_file"
    echo "$build_spec" >>"$md_file"
    echo '```' >>"$md_file"

    # Save to separate file
    echo "$build_spec" >"$OUTPUT_DIR/${app_name}-amplify.yml"
    log_info "Saved build spec to ${app_name}-amplify.yml"
  else
    echo "*No custom build spec (using framework defaults)*" >>"$md_file"
  fi
}

generate_markdown_branches() {
  local app_id=$1
  local app_name=$2
  local branches_json=$3
  local md_file=$4

  echo "" >>"$md_file"
  echo "#### Branches" >>"$md_file"
  echo "" >>"$md_file"

  local branch_count=$(echo "$branches_json" | jq -r '.branches | length')

  if [ "$branch_count" -eq 0 ]; then
    echo "*No branches configured*" >>"$md_file"
    return
  fi

  echo "| Branch | Framework | Stage | Auto Build | PR Preview | Last Deploy |" >>"$md_file"
  echo "|--------|-----------|-------|------------|------------|-------------|" >>"$md_file"

  echo "$branches_json" | jq -r '.branches[] | 
        "| `\(.branchName)` | \(.framework // "N/A") | \(.stage) | \(.enableAutoBuild) | \(.enablePullRequestPreview) | \(.updateTime) |"' >>"$md_file"

  # Get detailed branch info
  echo "" >>"$md_file"
  echo "**Branch Details:**" >>"$md_file"
  echo "" >>"$md_file"

  echo "$branches_json" | jq -r '.branches[].branchName' | while read -r branch_name; do
    log_info "  Getting details for branch: $branch_name"
    local branch_details=$(get_branch_details "$app_id" "$branch_name")

    echo "<details>" >>"$md_file"
    echo "<summary>Branch: $branch_name</summary>" >>"$md_file"
    echo "" >>"$md_file"
    echo '```json' >>"$md_file"
    echo "$branch_details" | jq '.branch' >>"$md_file"
    echo '```' >>"$md_file"
    echo "</details>" >>"$md_file"
    echo "" >>"$md_file"
  done
}

generate_markdown_domains() {
  local domains_json=$1
  local md_file=$2

  echo "" >>"$md_file"
  echo "#### Custom Domains" >>"$md_file"
  echo "" >>"$md_file"

  local domain_count=$(echo "$domains_json" | jq -r '.domainAssociations | length')

  if [ "$domain_count" -eq 0 ]; then
    echo "*No custom domains configured*" >>"$md_file"
    return
  fi

  echo "| Domain | Status | DNS Status |" >>"$md_file"
  echo "|--------|--------|------------|" >>"$md_file"

  echo "$domains_json" | jq -r '.domainAssociations[] | 
        "| `\(.domainName)` | \(.domainStatus) | \(.statusReason // "N/A") |"' >>"$md_file"

  # Subdomain details
  echo "" >>"$md_file"
  echo "**Subdomain Configuration:**" >>"$md_file"
  echo "" >>"$md_file"

  echo "$domains_json" | jq -r '.domainAssociations[] | .domainName as $domain | 
        .subDomains[] | 
        "- `\(.prefix).\($domain)` → Branch: `\(.branchName)`"' >>"$md_file"
}

generate_csv_row() {
  local type=$1
  local app_id=$2
  local app_name=$3
  local branch_name=${4:-""}
  local domain=${5:-""}
  local repo=${6:-""}
  local platform=${7:-""}
  local framework=${8:-""}
  local stage=${9:-""}
  local iam_role=${10:-""}
  local created=${11:-""}
  local updated=${12:-""}
  local notes=${13:-""}

  echo "\"$type\",\"$app_id\",\"$app_name\",\"$branch_name\",\"$domain\",\"$repo\",\"$platform\",\"$framework\",\"$stage\",\"$iam_role\",\"$created\",\"$updated\",\"$notes\"" >>"$OUTPUT_DIR/amplify-inventory.csv"
}

generate_import_commands() {
  local md_file=$1

  cat >>"$md_file" <<'EOF'

---

## Import Commands

Use these commands to import existing resources into Terraform:

```bash
#!/bin/bash
# Generated import commands for Terraform

set -e

REGION="us-east-1"
cd environments/production

EOF

  # Generate import commands for each app
  local app_ids=$(cat "$OUTPUT_DIR/apps-raw.json" | jq -r '.apps[].appId')

  for app_id in $app_ids; do
    local app_data=$(cat "$OUTPUT_DIR/app-${app_id}.json")
    local app_name=$(echo "$app_data" | jq -r '.app.name')

    cat >>"$md_file" <<EOF

echo "📦 Importing app: $app_name"

# Import Amplify App (adjust module path as needed)
terraform import 'module.amplify_app.aws_amplify_app.this[0]' "$app_id"

# Import IAM Role (if managing separately)
# terraform import 'module.amplify_app.aws_iam_role.default[0]' "${app_name}-amplify-role"

EOF

    # Import branches
    local branches=$(cat "$OUTPUT_DIR/app-${app_id}-branches.json" 2>/dev/null || echo '{"branches":[]}')
    echo "$branches" | jq -r '.branches[].branchName' | while read -r branch; do
      cat >>"$md_file" <<EOF
# Import branch: $branch
terraform import 'module.amplify_app.aws_amplify_branch.this["$branch"]' "${app_id}/${branch}"

EOF
    done

    # Import domains
    local domains=$(cat "$OUTPUT_DIR/app-${app_id}-domains.json" 2>/dev/null || echo '{"domainAssociations":[]}')
    echo "$domains" | jq -r '.domainAssociations[].domainName' | while read -r domain; do
      cat >>"$md_file" <<EOF
# Import domain: $domain
terraform import 'module.amplify_app.aws_amplify_domain_association.this["$domain"]' "${app_id}/${domain}"

EOF
    done
  done

  cat >>"$md_file" <<'EOF'

echo "✅ Import complete!"
echo "🔍 Running plan to verify..."
terraform plan
```

**Important Notes:**
- Adjust the import paths based on your module structure
- Review the plan output before applying
- Ensure your Terraform config matches the current state exactly
- Store secrets in AWS Secrets Manager, not in code

EOF
}

generate_next_steps() {
  local md_file=$1

  cat >>"$md_file" <<'EOF'

---

## Next Steps

### 1. Review Discovery Data
- [ ] Review this markdown report
- [ ] Check CSV file for inventory tracking
- [ ] Examine JSON files for detailed configs
- [ ] Review extracted `amplify.yml` build specs

### 2. Setup Secrets Management
```bash
# Store GitHub token
aws secretsmanager create-secret \
  --name amplify/github-token \
  --secret-string '{"token":"ghp_YOUR_TOKEN_HERE"}'

# Store environment variables
aws secretsmanager create-secret \
  --name amplify/production/env-vars \
  --secret-string '{"API_URL":"https://api.example.com"}'
```

### 3. Initialize Terraform
```bash
# Create Terraform configuration
mkdir -p terraform/environments/production
cd terraform/environments/production

# Copy template files and customize
# - main.tf
# - variables.tf
# - terraform.tfvars
# - backend.tf
```

### 4. Import Resources
```bash
# Run the import script from above
chmod +x import.sh
./import.sh

# Verify no drift
terraform plan
# Should show: No changes
```

### 5. Test Changes
```bash
# Make a small test change (add a tag)
terraform apply

# Verify in AWS console
```

### 6. Documentation
- [ ] Update team wiki with Terraform locations
- [ ] Document secret locations in Secrets Manager
- [ ] Create runbook for deployments
- [ ] Setup CI/CD for Terraform changes

---

## Useful Links

- [Amplify Terraform Provider Docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/amplify_app)
- [CloudPosse Amplify Module](https://github.com/cloudposse/terraform-aws-amplify-app)
- [Amplify Console](https://console.aws.amazon.com/amplify/)

---

**Report Generated:** $TIMESTAMP
EOF
}

################################################################################
# Main Execution
################################################################################

main() {
  log_section "AWS Amplify Discovery Script"

  # Pre-flight checks
  check_dependencies
  check_aws_credentials

  # Display configuration
  if [ -n "$AWS_PROFILE" ]; then
    log_info "Profile: $AWS_PROFILE"
  fi
  log_info "Region: $REGION"
  log_info "Account: $($AWS_CMD sts get-caller-identity --query Account --output text)"

  # Create output directory
  mkdir -p "$OUTPUT_DIR"
  log_info "Output directory: $OUTPUT_DIR"

  # Initialize output files
  local md_file="$OUTPUT_DIR/DISCOVERY-REPORT.md"
  local csv_file="$OUTPUT_DIR/amplify-inventory.csv"

  init_markdown "$md_file"
  init_csv "$csv_file"

  # Discover apps
  log_section "Discovering Amplify Apps"
  local app_ids=$(discover_amplify_apps)

  if [ -z "$app_ids" ]; then
    log_warn "No Amplify apps found in region $REGION"
    echo "No applications found in region $REGION" >>"$md_file"
    exit 0
  fi

  local app_count=$(echo "$app_ids" | wc -l | tr -d ' ')
  log_info "Found $app_count Amplify app(s)"

  # Save raw apps list
  $AWS_CMD amplify list-apps --region "$REGION" >"$OUTPUT_DIR/apps-raw.json"

  # Summary section
  cat >>"$md_file" <<EOF
**Total Applications:** $app_count  
**Discovery Date:** $TIMESTAMP

EOF

  echo "" >>"$md_file"
  echo "## Applications" >>"$md_file"

  # Process each app
  local app_number=1
  for app_id in $app_ids; do
    log_section "Processing App $app_number/$app_count: $app_id"

    # Get app details
    log_info "Fetching app details..."
    local app_json=$(get_app_details "$app_id")
    echo "$app_json" >"$OUTPUT_DIR/app-${app_id}.json"

    local app_name=$(echo "$app_json" | jq -r '.app.name')
    local repo=$(echo "$app_json" | jq -r '.app.repository // "N/A"')
    local platform=$(echo "$app_json" | jq -r '.app.platform // "WEB"')
    local iam_role=$(echo "$app_json" | jq -r '.app.iamServiceRoleArn // "N/A"')
    local created=$(echo "$app_json" | jq -r '.app.createTime')
    local updated=$(echo "$app_json" | jq -r '.app.updateTime')

    log_info "App Name: $app_name"

    # Generate markdown for app
    generate_markdown_app "$app_json" "$md_file"

    # CSV row for app
    generate_csv_row "App" "$app_id" "$app_name" "" "" "$repo" "$platform" "" "" "$iam_role" "$created" "$updated" ""

    # Get branches
    log_info "Fetching branches..."
    local branches_json=$(get_branches "$app_id")
    echo "$branches_json" >"$OUTPUT_DIR/app-${app_id}-branches.json"
    generate_markdown_branches "$app_id" "$app_name" "$branches_json" "$md_file"

    # CSV rows for branches
    echo "$branches_json" | jq -r '.branches[] | @json' | while read -r branch; do
      local branch_name=$(echo "$branch" | jq -r '.branchName')
      local framework=$(echo "$branch" | jq -r '.framework // "N/A"')
      local stage=$(echo "$branch" | jq -r '.stage')
      local branch_updated=$(echo "$branch" | jq -r '.updateTime')

      generate_csv_row "Branch" "$app_id" "$app_name" "$branch_name" "" "" "" "$framework" "$stage" "" "" "$branch_updated" ""
    done

    # Get domains
    log_info "Fetching domains..."
    local domains_json=$(get_domains "$app_id")
    echo "$domains_json" >"$OUTPUT_DIR/app-${app_id}-domains.json"
    generate_markdown_domains "$domains_json" "$md_file"

    # CSV rows for domains
    echo "$domains_json" | jq -r '.domainAssociations[]? | @json' 2>/dev/null | while read -r domain; do
      local domain_name=$(echo "$domain" | jq -r '.domainName')
      local domain_status=$(echo "$domain" | jq -r '.domainStatus')

      generate_csv_row "Domain" "$app_id" "$app_name" "" "$domain_name" "" "" "" "" "" "" "" "$domain_status"
    done

    # Get webhooks
    log_info "Fetching webhooks..."
    local webhooks_json=$(get_webhooks "$app_id")
    echo "$webhooks_json" >"$OUTPUT_DIR/app-${app_id}-webhooks.json"

    local webhook_count=$(echo "$webhooks_json" | jq -r '.webhooks | length')
    if [ "$webhook_count" -gt 0 ]; then
      echo "" >>"$md_file"
      echo "#### Webhooks" >>"$md_file"
      echo "" >>"$md_file"
      echo '```json' >>"$md_file"
      echo "$webhooks_json" | jq '.webhooks' >>"$md_file"
      echo '```' >>"$md_file"

      log_warn "App has $webhook_count webhook(s) - review before import"
    fi

    # Get backend environments
    log_info "Fetching backend environments..."
    local backends_json=$(get_backend_environments "$app_id")
    echo "$backends_json" >"$OUTPUT_DIR/app-${app_id}-backends.json"

    local backend_count=$(echo "$backends_json" | jq -r '.backendEnvironments | length')
    if [ "$backend_count" -gt 0 ]; then
      echo "" >>"$md_file"
      echo "#### Backend Environments" >>"$md_file"
      echo "" >>"$md_file"
      echo '```json' >>"$md_file"
      echo "$backends_json" | jq '.backendEnvironments' >>"$md_file"
      echo '```' >>"$md_file"

      log_warn "App has $backend_count backend environment(s) - may need additional Terraform resources"
    fi

    echo "" >>"$md_file"
    echo "---" >>"$md_file"

    ((app_number++))
  done

  # Generate import commands
  log_section "Generating Import Commands"
  generate_import_commands "$md_file"

  # Generate next steps
  log_section "Generating Next Steps"
  generate_next_steps "$md_file"

  # Summary
  log_section "Discovery Complete!"
  echo ""
  log_info "📄 Files generated:"
  log_info "   - $md_file (Main report)"
  log_info "   - $csv_file (Inventory spreadsheet)"
  log_info "   - $OUTPUT_DIR/*.json (Raw API responses)"
  log_info "   - $OUTPUT_DIR/*-amplify.yml (Build specifications)"
  echo ""
  log_info "🎯 Next: Review the markdown report and start Terraform migration"
  echo ""

  # Open markdown file if possible
  if command -v open &>/dev/null; then
    log_info "Opening report..."
    open "$md_file" 2>/dev/null || true
  elif command -v xdg-open &>/dev/null; then
    xdg-open "$md_file" 2>/dev/null || true
  fi
}

# Run main function
main "$@"
